name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write

jobs:
  start_exercise:
    name: Start Exercise
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.8.1
    with:
      exercise-title: "Hello GitHub Actions"
      intro-message: "Create and run a GitHub Actions workflow."
